const LOGINHANDLER="loginHandler";
const SIGNUPHANDLER= "signUpHandler";
const PASSPORTHANDLER="passportHandler";
const USERUPDATEIMAGEHANDLER ="userUpdateImageHandler";
const GROUPUPDATEIMAGEHANDLER ="groupUpdateImageHandler";
const GETPROFILEHANDLER="getProfileHandler";
const UPDATEPROFILEHANDLER="updateProfileHandler";

module.exports={
    LOGINHANDLER,
    SIGNUPHANDLER,
    PASSPORTHANDLER,
    USERUPDATEIMAGEHANDLER,
    GROUPUPDATEIMAGEHANDLER,
    GETPROFILEHANDLER,
    UPDATEPROFILEHANDLER,
};